[tool.poetry]
name = "python"
version = "0.1.0"
description = "app"
authors = ["franckDev21 <tutodevphp@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
